apiVersion: apps/v1
kind: Deployment
metadata:
  name: exploration-kubernetes-application
  labels:
    app: exploration-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exploration-kubernetes
  template:
    metadata:
      labels:
        app: exploration-kubernetes
    spec:
      containers:
        - name: exploration-kubernetes-application
          image: krzysztofkicinger/exploration-kubernetes:demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            timeoutSeconds: 5