apiVersion: v1
kind: Service
metadata:
  name: exploration-kubernetes-load-balancer
  labels:
    app: exploration-kubernetes
spec:
  type: LoadBalancer
  #  type: ClusterIP
  #  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
  selector:
    app: exploration-kubernetess